// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUTG5MW-rUKDttlWwner-I6i4dMNiGKec',
    appId: '1:332067839431:web:8f7c257802de38064a4de2',
    messagingSenderId: '332067839431',
    projectId: 'challanapp-6d31a',
    authDomain: 'challanapp-6d31a.firebaseapp.com',
    storageBucket: 'challanapp-6d31a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKVImaAbX_gHPn6uA_YnXE33AH5jMwve4',
    appId: '1:332067839431:android:5bf7ae5b508f33614a4de2',
    messagingSenderId: '332067839431',
    projectId: 'challanapp-6d31a',
    storageBucket: 'challanapp-6d31a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFESQd3vQWH1Pz7U3WP_jAhMgzTNOTqwQ',
    appId: '1:332067839431:ios:d5608c746c82fe3b4a4de2',
    messagingSenderId: '332067839431',
    projectId: 'challanapp-6d31a',
    storageBucket: 'challanapp-6d31a.firebasestorage.app',
    androidClientId: '332067839431-3gmm5mj870ddghbvfracnjv3610fo2g7.apps.googleusercontent.com',
    iosClientId: '332067839431-qan5q02schs1pkmmu83hsquifo7dop0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.challanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFESQd3vQWH1Pz7U3WP_jAhMgzTNOTqwQ',
    appId: '1:332067839431:ios:d5608c746c82fe3b4a4de2',
    messagingSenderId: '332067839431',
    projectId: 'challanapp-6d31a',
    storageBucket: 'challanapp-6d31a.firebasestorage.app',
    androidClientId: '332067839431-3gmm5mj870ddghbvfracnjv3610fo2g7.apps.googleusercontent.com',
    iosClientId: '332067839431-qan5q02schs1pkmmu83hsquifo7dop0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.challanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUTG5MW-rUKDttlWwner-I6i4dMNiGKec',
    appId: '1:332067839431:web:41e2c8d36ef7422f4a4de2',
    messagingSenderId: '332067839431',
    projectId: 'challanapp-6d31a',
    authDomain: 'challanapp-6d31a.firebaseapp.com',
    storageBucket: 'challanapp-6d31a.firebasestorage.app',
  );
}
